/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { ApiBooksGet$Plain$Params as ApiBooksGet$Plain$Params } from './fn/books/api-books-get-plain';
export { apiBooksGet$Plain as apiBooksGet$Plain } from './fn/books/api-books-get-plain';
export type { ApiBooksGet$Json$Params as ApiBooksGet$Json$Params } from './fn/books/api-books-get-json';
export { apiBooksGet$Json as apiBooksGet$Json } from './fn/books/api-books-get-json';
export type { ApiBooksPost$Params as ApiBooksPost$Params } from './fn/books/api-books-post';
export { apiBooksPost as apiBooksPost } from './fn/books/api-books-post';
export type { ApiBooksIdGet$Plain$Params as ApiBooksIdGet$Plain$Params } from './fn/books/api-books-id-get-plain';
export { apiBooksIdGet$Plain as apiBooksIdGet$Plain } from './fn/books/api-books-id-get-plain';
export type { ApiBooksIdGet$Json$Params as ApiBooksIdGet$Json$Params } from './fn/books/api-books-id-get-json';
export { apiBooksIdGet$Json as apiBooksIdGet$Json } from './fn/books/api-books-id-get-json';
export type { ApiBooksIdPut$Params as ApiBooksIdPut$Params } from './fn/books/api-books-id-put';
export { apiBooksIdPut as apiBooksIdPut } from './fn/books/api-books-id-put';
export type { ApiBooksIdDelete$Params as ApiBooksIdDelete$Params } from './fn/books/api-books-id-delete';
export { apiBooksIdDelete as apiBooksIdDelete } from './fn/books/api-books-id-delete';
