apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-api
  template:
    metadata:
      labels:
        app: backend-api
    spec:
      containers:
      - name: backend-api
        image: ghcr.io/pomodoro90/bookcatalog-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: MongoDbSettings__ConnectionString
          value: "mongodb://book-db-mongodb.default.svc.cluster.local:27017"